import type { Metadata } from "next";
import ComponentProviders from "@/providers/ComponentProviders";
import { FC, ReactNode } from "react";
import "./globals.css";

export const metadata: Metadata = {
  title: "Frontend Developer Code Challenge",
  description: "Generated by create next app",
};

type Props = {
  children: ReactNode;
};

const RootLayout: FC<Props> = ({ children }: Readonly<Props>) => {
  return <ComponentProviders>{children}</ComponentProviders>;
};

export default RootLayout;
